name: Code Linting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "source/**"
  push:
    branches:
      - master
      - develop
    paths:
      - "source/**"

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/master'
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"
          cancel_others: true

      - name: Check out code.
        uses: actions/checkout@main
  
      - name: Run clang format lint
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: "source"
          extensions: "cpp,hpp,h"
          clangFormatVersion: 16
          inplace: true

      - name: Run add and commit
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Code format - (Clang-format)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
